Do not log transitions if target is None
target=None is meant to only validate the source state.  This should not
get logged, and currently fails even:

> django.db.utils.IntegrityError: NOT NULL constraint failed: django_fsm_log_statelog.state